FROM python:3.9-slim-buster

WORKDIR /katyax

# copy all to workdir
COPY . .

RUN sudo apt-get install build-dep python-psycopg2

# install requirements
RUN pip install -r requirements.txt

# run the flask server
CMD ["python", "run_server.py"]