version: '3'

# create network with port 5000
networks:
  default:
    external:
      name: mynetwork

# create application of bot named katyax
services:
  katyax:
    image: katyax-1.0.0
    container_name: katyax
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
    env_file:
      - .env
    volumes:
      - .:/katyax   
  webserver:
    image: webserver-1.0.0
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile-flask
    restart: always
    networks:
      - default
    ports:
      - "8088:8088"
    env_file:
      - .env
    volumes:
      - .:/katyax